from dataclasses import dataclass, field
from typing import List, Optional, Dict

@dataclass
class Character:
    id: str
    name: str
    role: str
    appearance: str

@dataclass
class Environment:
    id: str
    name: str
    description: str

@dataclass
class SubtitleWord:
    text: str
    start_frame: int
    end_frame: int

@dataclass
class Sentence:
    text: str
    environment: str
    image_prompt: str
    # Generated during TTS and Image generation phases
    start_frame: int = 0
    end_frame: int = 0
    image_end_frame: int = 0
    image_file: str = ""
    words: List[SubtitleWord] = field(default_factory=list)

@dataclass
class ReelScript:
    """The raw script generated by the LLM."""
    title: str
    characters: List[Character] = field(default_factory=list)
    environments: List[Environment] = field(default_factory=list)
    sentences: List[Sentence] = field(default_factory=list)

@dataclass
class ReelManifest(ReelScript):
    """The completed script, including all media assets and timings."""
    audio_file: str = ""
    total_frames: int = 0

    @classmethod
    def from_script(cls, script: ReelScript) -> "ReelManifest":
        return cls(
            title=script.title,
            characters=script.characters,
            environments=script.environments,
            sentences=script.sentences,
        )
